# MySQL Condiguration

# URL database
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio2

# Name user and password database
spring.datasource.username=root
spring.datasource.password=Fran40556147!

# Display SQL statements in the console
spring.jpa.show-sql=true

# Update database and create entities
spring.jpa.hibernate.ddl-auto=update

# Hibernate generates optimized SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

# Security
jwt.secret = secret
jwt.expiration = 360000

# Conflicto con el @Bean
spring.main.allow-bean-definition-overriding=true
